FROM docker.io/nixos/nix:latest AS nix

RUN mkdir -p /build && printf 'experimental-features = nix-command flakes\n' >> /etc/nix/nix.conf
WORKDIR /build

# respecting flake.lock
#RUN cd /build && nix build github:aorith/neovim-flake \
#        && mkdir -p /build/neovim-flake-closure && cp -R $(nix-store -qR result/) /build/neovim-flake-closure/

# Neovim embedding config, plugins and deps
RUN cd /build && git clone --depth 1 https://github.com/aorith/neovim-flake && cd neovim-flake \
    && nix flake update && nix build . \
    && mkdir -p /build/neovim-flake-closure && cp -R $(nix-store -qR result/) /build/neovim-flake-closure/
