FROM quay.io/podman/stable:latest

RUN dnf install -y --nodocs --setopt install_weak_deps=false --exclude container-selinux \
        buildah \
        skopeo \
        jq \
    && dnf clean all \
    && rm -rf /var/log/dnf* /var/log/yum.* /var/cache
