FROM quay.io/podman/stable:latest

RUN dnf install -y --nodocs --setopt install_weak_deps=false buildah skopeo --exclude container-selinux \
    && dnf clean all \
    && rm -rf /var/log/dnf* /var/log/yum.* /var/cache
