FROM quay.io/toolbx/arch-toolbox:latest

ARG CURRENT_VERSION_REF

ENV CONTAINER_ID=archbox

LABEL "io.containers.autoupdate"="registry"

RUN host_bins=( \
        "cloud-localds" \
        "docker" \
        "firefox" \
        "flatpak" \
        "mpv" \
        "nix" \
        "nix-build" \
        "nix-channel" \
        "nix-collect-garbage" \
        "nix-copy-closure" \
        "nix-daemon" \
        "nix-env" \
        "nix-hash" \
        "nix-instantiate" \
        "nix-prefetch-url" \
        "nix-shell" \
        "nix-store" \
        "podman" \
        "rpm-ostree" \
        "systemctl" \
        "virsh" \
        "virt-install" \
        "vlc" \
        "wl-copy" \
        "wl-paste" \
        "xclip" \
        "xdg-open" \
        ); \
    for f in "${host_bins[@]}"; do \
        ln -s /usr/bin/distrobox-host-exec /usr/local/bin/"$f"; \
    done

# General tools
RUN pacman -Syu --noprogressbar --noconfirm --needed \
        age \
        bash \
        bash-completion \
        bat \
        bc \
        dos2unix \
        fd \
        fzf \
        iputils \
        kubernetes-tools \
        net-tools \
        nmap \
        python-boto3 \
        python-requests \
        python-urllib3 \
        rclone \
        ripgrep \
        rsync \
        skopeo \
        sops \
        terraform \
        the_silver_searcher \
        tmux \
        vim \
    && true

RUN pacman -Sc --noconfirm \
    && rm -rf /tmp/* \
    && echo "${CURRENT_VERSION_REF}" > /CURRENT_VERSION.txt \
    && echo "$(date +'%Y-%m-%d %H:%M:%S')" > /BUILD_DATE.txt
