FROM quay.io/toolbx-images/archlinux-toolbox:latest

ARG CURRENT_VERSION_REF

LABEL "io.containers.autoupdate"="registry"

COPY --from=ghcr.io/aorith/nvim-deps:latest /build/neovim-with-deps-closure/nix/store /nix/store
COPY --from=ghcr.io/aorith/nvim-deps:latest /build/dotfiles/topics/nvim/result/bin /tmp/nvim-bin
RUN for f in /tmp/nvim-bin/*; do ln -sf "$(realpath -- "$f")" /usr/local/bin/"$(basename -- "$f")"; done \
    && rm -rf /tmp/nvim-bin

RUN ln -s /usr/bin/distrobox-host-exec /usr/local/bin/rpm-ostree \
    && ln -s /usr/bin/distrobox-host-exec /usr/local/bin/podman \
    && ln -s /usr/bin/distrobox-host-exec /usr/local/bin/docker \
    && ln -s /usr/bin/distrobox-host-exec /usr/local/bin/flatpak \
    && ln -s /usr/bin/distrobox-host-exec /usr/local/bin/wl-copy \
    && ln -s /usr/bin/distrobox-host-exec /usr/local/bin/wl-paste \
    && ln -s /usr/bin/distrobox-host-exec /usr/local/bin/xclip

RUN pacman -Syu --noconfirm && pacman -S --noconfirm \
        bash \
        bash-completion \
        bat \
        bc \
        dos2unix \
        go \
        iproute2 \
        iputils \
        kubernetes-tools \
        neovim \
        net-tools \
        nmap \
        python-boto3 \
        python-requests \
        python-urllib3 \
        rsync \
        skopeo \
        starship \
        tmux \
        vim \
        yq \
    && echo "placeholder"

RUN pacman -Sc --noconfirm \
    && rm -rf /tmp/* \
    && echo "${CURRENT_VERSION_REF}" > /CURRENT_VERSION.txt \
    && echo "$(date +'%Y-%m-%d %H:%M:%S')" > /BUILD_DATE.txt
