# Dev environment using archlinux
# Shims are configured using distrobox-assemble in my dotfiles

FROM scratch AS ctx
COPY packages /packages

# https://github.com/containers/toolbox/blob/main/images/arch/Containerfile
FROM quay.io/toolbx/arch-toolbox:latest

LABEL io.containers.autoupdate="registry" \
      maintainer="aomanu+containers@gmail.com"

ENV CONTAINER_ID=archbox

# Init pacman and create build user
RUN printf "[multilib]\nInclude = /etc/pacman.d/mirrorlist\n" | tee -a /etc/pacman.conf && \
    sed -i 's/#MAKEFLAGS="-j2"/MAKEFLAGS="-j$(nproc)"/g' /etc/makepkg.conf && \
    pacman-key --init && pacman-key --populate && \
    pacman -Syu --noconfirm && \
    useradd -m --shell=/bin/bash build && usermod -L build && \
    mkdir -p /etc/sudoers.d && \
    echo "build ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/build && \
    echo "root ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/root

# Add yay
USER build
WORKDIR /home/build
RUN git clone https://aur.archlinux.org/yay.git --single-branch && \
    cd yay && \
    makepkg -si --noconfirm && \
    cd .. && \
    rm -rf yay

USER root
WORKDIR /

# Install packages
RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=tmpfs,dst=/tmp \
    pacman -Syu --needed --noconfirm - < /ctx/packages

# Cleanup
RUN sed -i 's@#en_US.UTF-8@en_US.UTF-8@g; s@#es_ES.UTF-8@es_ES.UTF-8@g' /etc/locale.gen && \
    userdel -r build && \
    rm -f /etc/sudoers.d/build \
    rm -f /etc/sudoers.d/root \
    rm -rf /home/build && \
    rm -rf /tmp/* && \
    pacman -S --noconfirm --clean --clean
