FROM docker.io/nixos/nix:latest AS nix

RUN mkdir -p /build
WORKDIR /build

# respecting flake.lock
#RUN cd /build && nix build --extra-experimental-features "nix-command flakes" github:aorith/neovim-flake \
#        && mkdir -p /build/neovim-flake-closure && cp -R $(nix-store -qR result/) /build/neovim-flake-closure/

# Neovim embedding config, plugins and deps
RUN cd /build && git clone --depth 1 https://github.com/aorith/neovim-flake && cd neovim-flake \
    && nix flake update && nix build --extra-experimental-features "nix-command flakes" . \
    && mkdir -p /build/neovim-flake-closure && cp -R $(nix-store -qR result/) /build/neovim-flake-closure/


# Neovim only embedding dependencies
RUN cd /build && git clone --depth 1 https://github.com/aorith/dotfiles && cd dotfiles/topics/nvim \
    && nix flake update && nix build --extra-experimental-features "nix-command flakes" . \
    && mkdir -p /build/neovim-with-deps-closure && cp -R $(nix-store -qR result/) /build/neovim-with-deps-closure/

