FROM docker.io/nixos/nix:latest AS nix

WORKDIR /tmp

# Neovim embedding config, plugins and deps
RUN nix build --extra-experimental-features "nix-command flakes" github:aorith/neovim-flake \
        && mkdir -p /tmp/neovim-flake-closure && cp -R $(nix-store -qR result/) /tmp/neovim-flake-closure/

# Neovim only embedding dependencies
RUN git clone --depth 1 https://github.com/aorith/dotfiles dotfiles \
    && cd dotfiles/topics/nvim && nix build --extra-experimental-features "nix-command flakes" . \
    && mkdir -p /tmp/neovim-with-deps-closure && cp -R $(nix-store -qR result/) /tmp/neovim-with-deps-closure/

