# ARGs must be redeclared between FROM statements
ARG FEDORA_MAJOR_VERSION
FROM quay.io/toolbx-images/fedora-toolbox:${FEDORA_MAJOR_VERSION}

ARG FEDORA_MAJOR_VERSION
ARG CURRENT_VERSION_REF

ENV CONTAINER_ID=fbox-slim

LABEL "io.containers.autoupdate"="registry"

RUN printf "\nfastestmirror=True\nmax_parallel_downloads=10\n" >> "/etc/dnf/dnf.conf" \
    && dnf -y distro-sync \
    && dnf install -y \
    "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-${FEDORA_MAJOR_VERSION}.noarch.rpm" \
    "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-${FEDORA_MAJOR_VERSION}.noarch.rpm" \
    && host_bins=( \
        "cloud-localds" \
        "docker" \
        "docker-compose" \
        "firefox" \
        "flatpak" \
        "mpv" \
        "nix" \
        "nix-build" \
        "nix-channel" \
        "nix-collect-garbage" \
        "nix-copy-closure" \
        "nix-daemon" \
        "nix-env" \
        "nix-hash" \
        "nix-instantiate" \
        "nix-prefetch-url" \
        "nix-shell" \
        "nix-store" \
        "podman" \
        "rpm-ostree" \
        "systemctl" \
        "virsh" \
        "virt-install" \
        "vlc" \
        "wl-copy" \
        "wl-paste" \
        "xclip" \
        "xdg-open" \
        ); \
    for f in "${host_bins[@]}"; do \
        ln -s /usr/bin/distrobox-host-exec /usr/local/bin/"$f"; \
    done

COPY ./dnf-packages /tmp/
RUN dnf update -y --refresh \
    && dnf install -y $(grep -Ev '^#' /tmp/dnf-packages | sort | uniq) "@Development Tools" \
    && dnf upgrade -y \
    && dnf clean all \
    && rm -rf /tmp/* \
    && ln -sf /run/host/mnt/storage /mnt/storage \
    && printf '%s\n%s' "${FEDORA_MAJOR_VERSION}-${CURRENT_VERSION_REF}" "$(date +'%Y-%m-%d %H:%M:%S')" > /CURRENT_VERSION
