ARG FEDORA_MAJOR_VERSION=latest

#FROM quay.io/toolbx-images/fedora-toolbox:${FEDORA_MAJOR_VERSION}
FROM registry.fedoraproject.org/fedora-toolbox:${FEDORA_MAJOR_VERSION}

ARG CURRENT_VERSION_REF

ENV CONTAINER_ID=fbox-slim

LABEL com.github.containers.toolbox="true" \
      maintainer="aomanu+containers@gmail.com"

RUN printf "\nfastestmirror=True\nmax_parallel_downloads=10\n" >> "/etc/dnf/dnf.conf" \
    && dnf -y distro-sync \
    && dnf install -y \
    "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm" \
    "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm"

COPY host-exec /
RUN grep -v '^#' /host-exec | sort | uniq | while read -r b; do ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/"$b"; done \
    && rm /host-exec

COPY packages /
RUN dnf update -y --refresh \
    && grep -v '^#' /packages | sort | uniq | xargs dnf install --setopt=install_weak_deps=False -y "@Development Tools" \
    && rm /packages \
    && dnf upgrade -y \
    && dnf clean all \
    && rm -rf /tmp/* \
    && printf '%s\n%s' "$(rpm -E %fedora)-${CURRENT_VERSION_REF}" "$(date +'%Y-%m-%d %H:%M:%S')" > /CURRENT_VERSION
