FROM quay.io/toolbx-images/archlinux-toolbox:latest

ARG CURRENT_VERSION_REF

LABEL "io.containers.autoupdate"="registry"

# COPY --from=ghcr.io/aorith/nvim-full:latest /build/neovim-flake-closure /nix/store
# COPY --from=ghcr.io/aorith/nvim-full:latest /build/result/bin/nvim /usr/local/bin/nvim

COPY --from=ghcr.io/aorith/nvim-deps:latest /build/neovim-with-deps-closure /nix/store
COPY --from=ghcr.io/aorith/nvim-deps:latest /build/dotfiles/topics/nvim/result/bin/* /usr/local/bin/

RUN useradd -m -G wheel builder && passwd -d builder \
    && curl -s --fail 'https://aur.archlinux.org/cgit/aur.git/snapshot/yay.tar.gz' -o /tmp/yay.tar.gz \
    && cd /tmp && tar xvf yay.tar.gz && cd /tmp/yay \
    && chown -R builder:builder /tmp/yay \
    && echo 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers \
    && su - builder -c "cd /tmp/yay && makepkg -si --noconfirm" \
    && ln -s /usr/bin/distrobox-host-exec /usr/local/bin/rpm-ostree \
    && ln -s /usr/bin/distrobox-host-exec /usr/local/bin/podman \
    && ln -s /usr/bin/distrobox-host-exec /usr/local/bin/docker \
    && ln -s /usr/bin/distrobox-host-exec /usr/local/bin/flatpak \
    && ln -s /usr/bin/distrobox-host-exec /usr/local/bin/wl-copy \
    && ln -s /usr/bin/distrobox-host-exec /usr/local/bin/wl-paste \
    && ln -s /usr/bin/distrobox-host-exec /usr/local/bin/xclip

RUN pacman -Syu --noconfirm && pacman -S --noconfirm \
        bash \
        bash-completion \
        bat \
        bc \
        dos2unix \
        go \
        iproute2 \
        iputils \
        kubernetes-tools \
        net-tools \
        nmap \
        python-boto3 \
        python-requests \
        python-urllib3 \
        rsync \
        skopeo \
        starship \
        tmux \
        vim \
    && echo "placeholder"

RUN su - builder -c "yay -S --noconfirm yq" \
    && su - builder -c "yay -Ycc --noconfirm" \
    && userdel builder && cd /tmp && rm -rf /tmp/yay \
    && pacman -Sc --noconfirm \
    && rm -rf /tmp/* \
    && echo "${CURRENT_VERSION_REF}" > /CURRENT_VERSION.txt \
    && echo "$(date +'%Y-%m-%d %H:%M:%S')" > /BUILD_DATE.txt
