FROM docker.io/library/alpine:latest

RUN apk add \
            bash \
            bind-tools \
            curl \
            wget \
            jq \
            mtr \
            socat \
            websocat \
            tcptraceroute \
            busybox-extras
