name: debugpod

on:
  workflow_dispatch:
  schedule:
    - cron: "11 03 * * 5"

concurrency:
  group: ${{ github.workflow }}

env:
  NAME: "debugpod"
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  DOCKER_BUILDKIT: "1"

jobs:
  push-ghcr:
    name: Build and push container images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Check out source
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64
          context: ${{ env.NAME }}
          file: ${{ env.NAME }}/Containerfile
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,scope=${{ github.workflow }}
          no-cache: ${{ github.run_attempt != '1' }}
          tags: ${{ env.IMAGE_REGISTRY }}/${{ env.NAME }}:latest
          push: true
          provenance: false
