name: debugpod

on:
  workflow_dispatch:
  schedule:
    - cron: "11 03 * * 5"

env:
  NAME: "debugpod"
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  push-ghcr:
    name: Build and push container images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout Push to Registry action
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.NAME }}
          file: ${{ env.NAME }}/Containerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.IMAGE_REGISTRY }}/${{ env.NAME }}:latest
          push: true
          provenance: false
